services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy

  csv-worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
      - WORKER_TYPE=csv
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy

  excel-worker:
    build:
      context: .
      dockerfile: docker/worker_2.Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
      - WORKER_TYPE=excel
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy

networks:
  app-network:
    driver: bridge

volumes:
  uploads:
  logs:
